create extension if not exists "pgcrypto";

create table if not exists public.student_profiles (
  id uuid primary key default gen_random_uuid(),
  display_name text not null check (char_length(display_name) between 2 and 40),
  grade_band text not null,
  avatar_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.interaction_history (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.student_profiles(id) on delete cascade,
  step_id text not null,
  response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.student_tags (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.student_profiles(id) on delete cascade,
  tag_type text not null,
  tag text not null,
  created_at timestamptz not null default now(),
  unique(profile_id, tag_type, tag)
);

create table if not exists public.pathway_recommendations (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.student_profiles(id) on delete cascade,
  archetype text not null,
  pathway_id text not null,
  rationale jsonb not null default '{}'::jsonb,
  generated_prompt text,
  created_at timestamptz not null default now()
);

create table if not exists public.discovery_results (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.student_profiles(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  character_brief jsonb not null default '{}'::jsonb,
  website_prompt text not null,
  created_at timestamptz not null default now()
);

alter table public.student_profiles enable row level security;
alter table public.interaction_history enable row level security;
alter table public.student_tags enable row level security;
alter table public.pathway_recommendations enable row level security;
alter table public.discovery_results enable row level security;

create policy "anonymous journey profile insert" on public.student_profiles for insert to anon with check (true);
create policy "anonymous journey interaction insert" on public.interaction_history for insert to anon with check (true);
create policy "anonymous journey tags insert" on public.student_tags for insert to anon with check (true);
create policy "anonymous journey pathway insert" on public.pathway_recommendations for insert to anon with check (true);
create policy "anonymous discovery result insert" on public.discovery_results for insert to anon with check (true);
